name: Containerize site

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build website
        run: |
              npm install
              mkdir -p dist
              cp -r node_modules/tuicss/dist/* dist/
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push container
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/paolomazzon/portfolio:latest
            ghcr.io/paolomazzon/portfolio:${{ github.sha }}