name: Containerize site

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  packages: write

jobs:
  Containerize:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Build website
        run: |
              npm install
              npm run build
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push container
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/paolomazzon/portfolio:dev-latest
            ghcr.io/paolomazzon/portfolio:${{ github.sha }}
      - name: Deploy to test env
        run: |
              curl -f \
                -X POST \
                -H "${{ secrets.K8S_HEADER_AND_CLIENT_ID }}" \
                -H "${{ secrets.K8S_CLIENT_HEADER_AND_SECRET }}" \
                https://api.paolomazzon.dev/deploy/dev